spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  application:
    name: ownership-service
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

server:
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/swagger.html"