apiVersion: v1
kind: Service
metadata:
  name: ownership-service-service
spec:
  selector:
    app: ownership-service
  ports:
    - port: 8092
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownership-service-deployment
  labels:
    app: ownership-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ownership-service
  template:
    metadata:
      labels:
        app: ownership-service
    spec:
      containers:
        - name: ownership-service
          #          image: 'wavsharecontainerregistry.azurecr.io/wavshare-ownershipservice/wavshare-ownershipservice:latest'
          image: 'k3d-wavshare:5000/ownershipservice:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ownership-service-secret
                  key: mongo-uri
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ownership-service-secret
                  key: mongo-database
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: host
            - name: RABBIT_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: port
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password

